spring:
  cassandra:
    keyspace-name: cbkeyspace
    port: 9042
    contact-points: 127.0.0.1
    local-datacenter: datacenter1
    schema-action: CREATE_IF_NOT_EXISTS
  # SWAGGER
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs
# LOGGING
logging:
  level:
    com.cb: TRACE

